---
collections:
  - name: community.general
    version: 10.7.7
  - name: community.sops
    version: 2.2.7
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: kubernetes.core
    version: 6.3.0
roles:
  - name: githubixx.cilium_cli
    version: 3.0.0+0.18.5
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: static-pods
